apiVersion: kopf.dev/v1
kind: MLFlow
metadata:
  name: lstm-pipeline
spec:
  pipeline:
    stage1:
      name: data-preprocess
      step:
      - name: time-parser
        mlfun: james759426/time-parser:0.0.1
      - name: data-clean
        mlfun: james759426/data-clean:0.0.1
    stage2:
      name: LSTM-model-build
      step:
      - name: train-data-build
        mlfun: james759426/train-data-build:0.0.1
      - name: train-model-build
        mlfun: james759426/train-model-build:0.0.1
      - name: train-model
        mlfun: james759426/train-model:0.0.1
    stage3:
      name: model-serveing
      step:
      - name: model-serveing-fun
        mlfun: james759426/model-serveing-fun:0.0.1
